### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by dboyz** [prawnsalad/KiwiIRC#212]
Implement some keyboard shortcuts such as:

Ctrl + F4 = Close current window
Alt + [Num] = Switch to window [Num]

and etc. The above shortcuts are only example.

**Comment by jcrben** [comment]
Hi @prawnsalad - is it possible to page up or down the input? That would be the best. For example typically I can use fn+up for pgup on my Macbook but that isn't working...
