### ISSUE TITLE
Issue with channel key from front page - Works with command line

### ISSUE THREAD

**Issue by michaelopdenacker** [prawnsalad/KiwiIRC#469]
Hi,

I'm using the latest git commit as of today

I don't manage to connect to a key protected channel by specifying the key on the front page.

I do have a tab that's trying to connect to the channel, but it seems to try connecting to the channel forever (no error message).

If I connect from the server tab ("/join #channel key"), it just works.

This is related to issue #391, which did fix an earlier error, but failed to make the whole thing work (at least for me).

Don't hesitate to let me know how I could help finding the cause of this issue. I'll be happy to share logs or debugging info.

Thank you for your support and for this nice piece of software!

Michael.

As the error is gone, I'll open a new issue for this.

**Comment by prawnsalad** [comment]
Note sure when this was fixed or if there was a cause, but it now appears to be working without issue. /late

**Comment by michaelopdenacker** [comment]
On 03/12/2015 20:08, Darren wrote:
>
> Closed #469 <https://github.com/prawnsalad/KiwiIRC/issues/469>.
>

I confirm. Thanks a lot!

Michael.

-- 
Michael Opdenacker, CEO, Free Electrons
Embedded Linux, Kernel and Android engineering
http://free-electrons.com
+33 484 258 098
