### ISSUE TITLE
Ability to connect to multiple servers simultaneously

### ISSUE THREAD

**Issue by StFS** [prawnsalad/KiwiIRC#493]
Many apologies if this is already possible or if a feature request for this already exists. However, I tried looking for it but couldn't find anything.

So I basically just want to be able to connect to multiple IRC servers / networks at once.

**Comment by rodneyrod** [comment]
This should be a GUI option, this bug should be opened again.

**Comment by brodycas3** [comment]
I agree, There should be a button to connect to another server for users that don't know this.
