### ISSUE TITLE
Kiwi doesn't reconnect

### ISSUE THREAD

**Issue by martinszy** [prawnsalad/KiwiIRC#547]
Sometimes my machine losses connection (suspended state, for instance) and kiwi disconnects from the server. Then it attempts to reconnect, but it can't.
Here's the output in the server console: 
[396] gateway/web/cgi-irc/kiwiirc.com/ip.XXX , is now your hidden host (set by syn.)
You have been disconnected. Attempting to reconnect again in 2 seconds...
You have been disconnected. Attempting to reconnect for you...
You have been disconnected. Attempting to reconnect again in 2 seconds...
You have been disconnected. Attempting to reconnect for you...
You have been disconnected. Attempting to reconnect again in 4 seconds...
You have been disconnected. Attempting to reconnect again in 8 seconds...
You have been disconnected. Attempting to reconnect again in 16 seconds...
You have been disconnected. Attempting to reconnect again in 32 seconds...

**Comment by Enamex** [comment]
Still an issue. Anyway to manually reconnect? Writing `/server irc.mozilla.org` after disconnecting while being in rooms on that server, for example, doesn't do anything.

**Comment by prawnsalad** [comment]
What browser and OS are you using for this?

**Comment by Enamex** [comment]
Latest Chrome Beta on Windows 8.1. Tried with no extensions running at all so it's not that.

**Comment by deathgaze** [comment]
This is still an issue.

**Comment by calincru** [comment]
has this been addressed?

**Comment by chrismarsh08** [comment]
Still an issue.
