### ISSUE TITLE
Put nickname into input field when clicking on it

### ISSUE THREAD

**Issue by fireton** [prawnsalad/KiwiIRC#573]
When I click on the someone's nickname in the main chat window, kiwiirc popup a menu with options like ban, kick, etc. - the same menu as when clicking on nickname in the user list. 

It would be great if instead of this kiwiirc would just put this name into message input field with comma after it. So I could easily address other person in the chat.

**Comment by prawnsalad** [comment]
Will keep this working as-is but an example plugin to change to it to insert the nick into the control input as requested instead: https://kiwiirc.com/docs/scripting/examples
