### ISSUE TITLE
Color Formatting

### ISSUE THREAD

**Issue by Namasteh** [prawnsalad/KiwiIRC#579]
One of the biggest features that IRC users like is color formatting the text they send to the server. That is the only thing this client is lacking

**Comment by tafufo** [comment]
I have those files in my plugins folder.
How to enable to appear in the client browser ??

**Comment by prawnsalad** [comment]
@tafufo You can find how to enable them here https://kiwiirc.com/docs/scripting/client_plugins

**Comment by tafufo** [comment]
I did like that page and restart kiwi and no appear like kiwi.chathispano.com

**Comment by prawnsalad** [comment]
@tafufo I don't see the textstyle plugin your live config. Make sure your kiwi server has been restarted since changing the config. If that dosn't work then you might want to ask on the mailing list with a paste of your config.js file.

https://groups.google.com/d/forum/kiwiirc

**Comment by tafufo** [comment]
I got it. Thank you.
> conf.client_plugins = [
> '/kiwi/assets/plugins/textstyle.html',
> '/kiwi/assets/plugins/filepicker.html',
> '/kiwi/assets/plugins/emoticonlist.html'
> ];
> 
The filepicker show the icon, after clicking displays an error.

Apikey: YOUR_API_KEY not found


???

**Comment by CoryChaplin** [comment]
File picker is a SaaS solution that requires you have a dev account.
Go there, sign up and get an API key.

-- 
Elephantman

De :  tafufo <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5d9226ce7d98ae02fec060f582fff677b9b6a84b292cf0000000112d445649
2a169ce02642aea@reply.github.com>
Date :  jeudi 11 février 2016 13:49
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  Re: [KiwiIRC] Color Formatting (#579)
