### ISSUE TITLE
Actual Nick not shown during the replay of backlogs or buffers

### ISSUE THREAD

**Issue by vijaiaeroastro** [prawnsalad/KiwiIRC#589]
![undefined](https://cloud.githubusercontent.com/assets/2363451/4107641/b8bcf0f8-31ca-11e4-9a75-8996e8480e5b.png)
 
During the playback of buffer by my bouncer, all the actions are shown as above without a nick.
It shows "undefined" instead of the nicks.

**Comment by prawnsalad** [comment]
@vijaiaeroastro Is this still an issue on kiwiirc.com/client/ ?

**Comment by vijaiaeroastro** [comment]
@prawnsalad I switched to znc a long back. I will try to run another relay later and see if the issue still persists.
