### ISSUE TITLE
DCC download feature

### ISSUE THREAD

**Issue by leni1** [prawnsalad/KiwiIRC#591]
This is for providing the DCC file transfer feature in the KiwiIRC client.

**Comment by iz8mbw** [comment]
Hi.
Any news about the DCC file transfer feature?
Thanks!

**Comment by leni1** [comment]
Not that I know of.

**Comment by q4a** [comment]
Must have feature missing =(

**Comment by prawnsalad** [comment]
Closing since DCC over a web client just isn't feasible.

For anyone reading this in future - take a look at the next version of kiwiirc at https://github.com/kiwiirc/kiwiirc which is now far more capable than this
