### ISSUE TITLE
'Are you sure you want to change page' dialogue disconnects Kiwirc in Chrome

### ISSUE THREAD

**Issue by reality** [prawnsalad/KiwiIRC#609]
Steps to reproduce:

1. Connect to a server using Kiwi in Chrome
2. Click on a bookmark, or type an address e.g. google.com into the address bar and press enter
3. Note that Kiwi disconnects from the server when the confirmation dialogue appears

Dialogue can be used without incident using Firefox

**Comment by prawnsalad** [comment]
Unfortunately this can't be worked around in chrome. (Couldn't detect it at the time as you have to wait a fair amount of time before the disconnect..) /late
