### ISSUE TITLE
kiwiirc won't connect to dalnet

### ISSUE THREAD

**Issue by cjvalas** [prawnsalad/KiwiIRC#626]
It simply hangs at the 'Connecting' stage - no timeout, nothing.

Checked dalnet from other client environment -- no problem -- they connect fine.

**Comment by prawnsalad** [comment]
This looks OK now. It was most likely either a config or server issue somewhere. If you have any network issues the mailing list is a better place to ask: https://groups.google.com/d/forum/kiwiirc
