### ISSUE TITLE
Shit locked on Firefox

### ISSUE THREAD

**Issue by eatyourpotato** [prawnsalad/KiwiIRC#632]
Hello. 

I have encountered what must be the weirdest bug, and maybe not directly related to kiwiirc.
On firefox with windows 7 if the cursor is not in the textbox and I press the right shift to capitalize the first letter of my message, firefox acts like the right shift is still pressed only for firefox until I press the left shift. This is not a keyboard issue because in the same time if I switch to another application, the input works normally.
On a previous computer of another company, I also had this issue with Windows+Firefox even if it wasn't happening every time.
Do you think it's a bug induced by the library used by to kiwiirc to catch the input when the textbox is not focused? I haven't met this behavior anywhere else.
I am using Firefox 24 because of company policies, on Windows 7 pro.

**Comment by prawnsalad** [comment]
Closing this issue since I can't replicate it anywhere.

**Comment by eatyourpotato** [comment]
Hello,

I've just updated Firefox to the version 36.0.4 and it is still happening and it's really puzzling me. I've even managed to reproduce this bug with the virtual keyboard of Seven. The process is very simple :
- open any chan
- click on the text to set the focus there and not in the text area 
- Just press the right shit key once
-> Firefox will now act as if the right shift key is pressed down all the time.
- Just press the left shift key one
-> Firefox will behave normally
So I think you're right, I seems to come from Firefox, but I couldn't replicate this bug anywhere else.
