### ISSUE TITLE
No support for messages sent to specific channel statuses

### ISSUE THREAD

**Issue by webczat** [prawnsalad/KiwiIRC#634]
Hello.
In most current ircds it is possible to, being on a channel, send privmsgs or notices to users of the channel with a certain (and higher) status like +, %, @, & or ~.
Syntax: PRIVMSG|NOTICE <statuschar>#channel :message

for example
NOTICE +#test :hibiscus: 
The problem is that the client does not display such messages in the channel window when someone receives them.

**Comment by prawnsalad** [comment]
Now in development branch, due in a minor release any time now. https://github.com/prawnsalad/KiwiIRC/commit/0e037c7304eb158bfde8f5ed512680745732e84f
