### ISSUE TITLE
issues of keyboard navigation

### ISSUE THREAD

**Issue by webczat** [prawnsalad/KiwiIRC#635]
Kiwiirc, when any key with some exceptions is pressed, focus changes to the input box.
Unfortunately, it partially conflicts with screen reader that I am using, because not only letters cause that, but also pressing shift alone and that is really annoying, especially that sometimes it also triggers a rare screenreader bug.
In addition pressing arrows also causes this, and it becomes annoying when for example trying to change a language with a keyboard.
I would suggest focus to be changed to the input field only if a small or capital letter is pressed, not on shift/arrows/etc.

**Comment by prawnsalad** [comment]
Some time later.. but the focus is no longer shifted when any form element currently has focus. Due to be live on kiwiirc.com/client any time now. Thanks!
