### ISSUE TITLE
Use LocalStorage for logs

### ISSUE THREAD

**Issue by SoniEx2** [prawnsalad/KiwiIRC#642]
That way we can get _local_ logs (not server-side) on a webclient!

**Comment by CoryChaplin** [comment]
Can you be more explicit ? Kiwiirc already uses localstorage for settings.

**Comment by SoniEx2** [comment]
Logs?

**Comment by tezeri** [comment]
I agree with this. It would be rather nice to have logs stored locally on the machine. It would also be nice to have a way to possibly export them from LocalStorage if the store gets too full.

**Comment by prawnsalad** [comment]
Closing this as it's unfortunately currently not feasible with todays browsers. Writing to LocalStorage all the time can slow things down and with not much available space. Will re-evaluate this in future for client-side logging.
