### ISSUE TITLE
Feature request: different nick highlighting on dark themes

### ISSUE THREAD

**Issue by spadgos** [prawnsalad/KiwiIRC#648]
When using a dark theme, some nicknames are impossible to read:

![selection_012](https://cloud.githubusercontent.com/assets/426222/5615678/d4ed8cba-94fd-11e4-8bb7-fc22f52da7c6.png)

If it were possible for the themes to flag that they're a dark theme, then the `getNickStyles` method could use a different lightness value. Right now, it's hardcoded to lightness = 35.

```js
rgb = hsl2rgb(nick_int % 256, 70, 35);
```

**Comment by prawnsalad** [comment]
Theme options now merged into development branch
