### ISSUE TITLE
very broken

### ISSUE THREAD

**Issue by DreadKnight** [prawnsalad/KiwiIRC#652]
I have kiwiIRC on my website and for quite a few days now it's broken https://AncientBeast.com/chat
It connects to the channel but you don't see the messages and also your own imputed messages don't get sent. So it's basically useless. I'll probably revert to the initial qwebirc applet soon if I can't find a fix :-\

**Comment by prawnsalad** [comment]
As mentioned on IRC, this was an issue with the romanian translation. Fixed. Thanks for the report!

**Comment by DreadKnight** [comment]
Good job, hopefully the fix will go live soon.

**Comment by prawnsalad** [comment]
It is live already. Make sure your browser cache is cleared and you should be good to go

**Comment by DreadKnight** [comment]
Yeah, just tried it out, it works. Didn't had to delete cache, just thought
the push will take a quite a while to get approved xD

2015-01-17 1:27 GMT+02:00 Darren <notifications@github.com>:

> It is live already. Make sure your browser cache is cleared and you should
> be good to go
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/prawnsalad/KiwiIRC/issues/652#issuecomment-70339379>.
>



-- 

Dread Knight
about.me/DreadKnight
[image: Dread Knight on about.me]
  <http://about.me/DreadKnight>




<http://about.me/DreadKnight>
