### ISSUE TITLE
Problem listing channels on irc.inspircd.org

### ISSUE THREAD

**Issue by jdeveloper** [prawnsalad/KiwiIRC#656]
Connecting with KiwiIRC to irc.inspircd.org when listing channels there are 2 problems.

First, when you enter /list then to tabs are opened. One with the list of the channels

![list_channels1](https://cloud.githubusercontent.com/assets/8874/5797689/0adebbca-9fbf-11e4-9690-6acc3c2c016a.png)

And one tab with the search box and it doesn't filter the channels at all.

![list-channels2](https://cloud.githubusercontent.com/assets/8874/5797703/42066a9e-9fbf-11e4-810e-d280c9bff3bf.png)

The second problem is that once you close the list channels tab, when you enter /list again, the tab isn't open anymore.

**Comment by CoryChaplin** [comment]
Hi,

This issue exists on kiwiirc.com for networks that donc have a « homemade »
channel list.
For the major networks like FreeNode, kiwiirc.com has made a web service
that returns the list and that works fine.

Cory

De :  jdeveloper <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5dcc10340921c8a40db6492fd8d1fd256cc0be03292cf0000000110d485899
2a169ce03433da4@reply.github.com>
Date :  lundi 19 janvier 2015 09:42
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [KiwiIRC] Problem listing channels on irc.inspircd.org (#656)

**Comment by prawnsalad** [comment]
Hi, just checking if this is working fine for you now? It should only be opening 1 tab when running /list

**Comment by jdeveloper** [comment]
Yes, it works now, thanks.
