### ISSUE TITLE
Kiwi reconnect does not rejoin keyed channels

### ISSUE THREAD

**Issue by MyWay** [prawnsalad/KiwiIRC#664]
If you ./kiwi restart, when kiwi reconnects the users, they cannot rejoin channels with a key (even if the key is the config file), it says that the key is wrong.

**Comment by MyWay** [comment]
Sorry, I've noticed now that this is a duplicate of #614.

**Comment by prawnsalad** [comment]
Not a duplicate, that's referring to a server password while you mention a channel key. Re-joining with a channel key is now in the development branch and will be included in the next minor kiwi release any day now.
