### ISSUE TITLE
Blank page for some mobile users

### ISSUE THREAD

**Issue by MyWay** [prawnsalad/KiwiIRC#665]
Some users are getting a blank page (e.g. on http://kiwiirc.com/client) when connecting from a smartphone. I've tried with the android emulator 2.3.3, using the default browser, but satdav reported that this happens on some kitkat device and Mikaela from Sailfish OS v1.1.1.27, too.

**Comment by MyWay** [comment]
Here is the logcat from the emulator (Android 2.3.3):
02-01 16:07:13.323    1211-1211/com.android.browser E/browser﹕ Console: SyntaxError: Parse error https://kiwiirc.com/client/src/helpers/plugininterface.js:243
02-01 16:07:15.503    1211-1211/com.android.browser E/browser﹕ Console: SyntaxError: Parse error https://kiwiirc.com/client/src/views/channel.js:468
02-01 16:07:16.133    1211-1211/com.android.browser E/browser﹕ Console: SyntaxError: Parse error https://kiwiirc.com/client/src/views/memberlist.js:97
02-01 16:07:19.293    1211-1211/com.android.browser E/browser﹕ Console: undefined https://kiwiirc.com/client/src/app.js:255

**Comment by MyWay** [comment]
04-02 00:40:26.470    1239-1239/system_process E/browser﹕ Console: SyntaxError: Parse error kiwi/src/views/channel.js:483
04-02 00:40:26.570    1239-1239/system_process E/browser﹕ Console: SyntaxError: Parse error kiwi/src/views/memberlist.js:97
04-02 00:40:27.330    1239-1239/system_process E/browser﹕ Console: SyntaxError: Parse error kiwi/src/helpers/plugininterface.js:243
04-02 00:40:27.640    1239-1239/system_process E/browser﹕ Console: undefined kiwi/src/app.js:256

**Comment by prawnsalad** [comment]
Looks like it's caused by using the `.catch` keyword that older browsers catch... will update this soon to get them supported

**Comment by MyWay** [comment]
Any news?

**Comment by prawnsalad** [comment]
Completely forgot about this sorry! Have pushed some changes to the development branch if you want to give it a try?

**Comment by MyWay** [comment]
Sure, I confirm that now it's working, thank you.
