### ISSUE TITLE
Error: Cannot find module 'daemonize2'

### ISSUE THREAD

**Issue by weegaz** [prawnsalad/KiwiIRC#670]
i have problem with install KiwiIRC on CentOS
Error: Cannot find module 'daemonize2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/luv/public_html/chat/KiwiIRC/server/helpers/launcher.js:20:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by M2Ys4U** [comment]
Have you run `npm install`?

**Comment by weegaz** [comment]
yes i did but you need as a root or user ?

**Comment by weegaz** [comment]
as a root 
npm http GET https://registry.npmjs.org/es6-promise
npm http GET https://registry.npmjs.org/daemonize2/0.4.2
npm http GET https://registry.npmjs.org/po2json/0.3.0
npm http GET https://registry.npmjs.org/engine.io
npm http GET https://registry.npmjs.org/socksjs/0.4.4
npm http GET https://registry.npmjs.org/spdy/1.19.1
npm http GET https://registry.npmjs.org/uglify-js/2.4.12
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/iconv-lite/0.4.4
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/ipaddr.js/0.1.3
npm http GET https://registry.npmjs.org/negotiator/0.4.3
npm http GET https://registry.npmjs.org/node-static/0.7.4
npm http 304 https://registry.npmjs.org/es6-promise
npm ERR! Error: No compatible version found: es6-promise@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.1.1","0.1.2","1.0.0","2.0.0","2.0.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.j                                                                                        s:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry                                                                                        -client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/luv/public_html/chat/KiwiIRC
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm http 304 https://registry.npmjs.org/daemonize2/0.4.2
npm http 304 https://registry.npmjs.org/engine.io
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/iconv-lite/0.4.4
npm http 304 https://registry.npmjs.org/spdy/1.19.1
npm http 304 https://registry.npmjs.org/po2json/0.3.0
npm http 304 https://registry.npmjs.org/socksjs/0.4.4
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/ipaddr.js/0.1.3
npm http 304 https://registry.npmjs.org/negotiator/0.4.3
npm http 304 https://registry.npmjs.org/uglify-js/2.4.12
npm http 304 https://registry.npmjs.org/node-static/0.7.4
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/luv/public_html/chat/KiwiIRC/npm-debug.log
npm ERR! not ok code 0

**Comment by M2Ys4U** [comment]
Just as a regular user, when you're in the `KiwiIRC` directory.

Also, I've just noticed that you have put the `KiwiIRC` directory inside `public_html` - this is usually a bad idea. Kiwi uses a built-in web server.

**Comment by M2Ys4U** [comment]
That version of npm is old. Try updating it by running `npm install -g npm@latest`. You may need to do this as `root`.

**Comment by weegaz** [comment]
ok thank you for help ;)
