### ISSUE TITLE
Inspircd & kiwiIRC work together?

### ISSUE THREAD

**Issue by Chrysweel** [prawnsalad/KiwiIRC#671]
Hello.

I do not know where to put this issue, but I am crazy this problem. I put it here to see if anyone else has tried.

I opened other issue in repo inspircd ( https://github.com/inspircd/inspircd/issues/996 )

I have inspircd ( https://github.com/inspircd/inspircd ) and irc client kiwiIRC

But I have a problem.
Some users are connected even after you close the browser.

I have inspircd and KiwiIRC with config by default.

I think that problem is : inspircd not throw the user disconnection event or kiwiIRC not collect that event to close the connection.

Has anyone tried inspircd and kiwiIRC together?

Thanks by advance.

**Comment by CoryChaplin** [comment]
Hi,

What setting do you have for conf.ircd_reconnect ?
There are known issues of this kind with that option, you should probably
have it set to false.

-- 
Elephantman

De :  Chrysweel <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5dc4c27728faee9736f9e3e3aee2d2091dd71039492cf0000000110fc29459
2a169ce0375c464@reply.github.com>
Date :  mercredi 18 février 2015 11:19
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [KiwiIRC] Inspircd & kiwiIRC work together? (#671)

**Comment by Chrysweel** [comment]
@CoryChaplin thanks for replying.
This is my param in config of kiwii
```
/*
* Auto reconnect if the IRC server disconnects a kiwi user
* Hundreds of connected users getting disconnected then reconnecting at once may see
* high CPU usage causing further dropouts. Set to false if under high usage.
*/
conf.ircd_reconnect = true;
```

I try changing the parameter to false value?

**Comment by CoryChaplin** [comment]
Yep, should help a lot.

-- 
Elephantman

De :  Chrysweel <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5d6f5eb92de0025f3dd6a6f0634829225cd5503e992cf0000000110fc2bbc9
2a169ce0375c464@reply.github.com>
Date :  mercredi 18 février 2015 11:30
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Cc :  Cory CHAPLIN <elephantman@europnet.org>
Objet :  Re: [KiwiIRC] Inspircd & kiwiIRC work together? (#671)

**Comment by Chrysweel** [comment]
With ircd_reconnect to false. The number of users connected is now correct.

But I contiue with other problem... with ~265 users If I have ~1000 sockets opened is normal ? Or are there some problem ? 

I need to increase the "ulimit -n" ... is correct ? That number ulimit is recommended?

Thanks in advance

**Comment by prawnsalad** [comment]
Could you create a new issue for ircd_reconnect keeping connections open please?

Each user may have at minimum 2 socket connections depending on the browser and many other things. 1) websocket, 2) any other browser requests (may be kept open by keep-alive), 3) kiwi->ircd socket.

If you're using SSL I believe that's an extra socket per user also.

**Comment by Chrysweel** [comment]
I have 1985 files opened ( 1670 sockets ) with 317 users..
Is it possible ? Anyone have similar data?
