### ISSUE TITLE
corresponding source to minified js files

### ISSUE THREAD

**Issue by joshuagay** [prawnsalad/KiwiIRC#673]
I am unable to find the source to some of the minified JS files, such as backbone.min.js and query-1.11.1.min.js. I know that I could get the source versions from those respective projects.In general, though, if a person distributes the minified JS files with a project they should also distibute the corresponding source that were used to generate those minified JS files. I apologize if this issue was created in error and the corresponding source is in fact being provided alongside the minified versions. Thank you in advance! This is a very cool project.

**Comment by prawnsalad** [comment]
We don't include the unminified sources, you're correct. Is this a license thing saying that we need to include the unminified versions in this repo? Can't say I've seen any other project include them if not needed.
