### ISSUE TITLE
Hide IRC messages

### ISSUE THREAD

**Issue by ircer** [prawnsalad/KiwiIRC#677]
Hi, 

I moved some chat websites from lightIRC to KiwiIRC. The users don't really know what IRC is since they  just think of it as some chatroom.

A good thing on lightIRC was being able to hide IRC messages:

6:31:40 PMⓘ ChanServ set mode +o admin7
6:31:52 PMⓘ admin7 set mode +b *!*@24-212-194-15.cable.teksavvy.com 
6:31:52 PM← Gina` was kicked by admin7 (Banned) 

Is there any way to do it in KiwiIRC?

I'm using custom client registered on kiwiirc.com

**Comment by prawnsalad** [comment]
It is possible to hide message using a plugin but we don't allow custom plugins to be used on kiwiirc.com just yet.

I'm sure a simple plugin could be put together that allows people to hide/ban specific words or phrases and put into the plugin list for your custom clients (might do this soon actually) so you might want to keep an eye on the @kiwiirc twitter account or mailing list for when that's available.
