### ISSUE TITLE
iPhone Safari issues

### ISSUE THREAD

**Issue by ghost** [prawnsalad/KiwiIRC#679]
iPhone in landscape mode: 

1. Hitting send a message to type a message doesn't work. No keyboard, nothing - impossible to send a message. 

2. Scrolling up or down the nickname list doesn't work - pulls the whole window up or down. 

3. Scrolling up or down the chat window doesn't work - pulls the whole window up or down.

**Comment by MyWay** [comment]
I think this is the same as https://github.com/prawnsalad/KiwiIRC/issues/663

**Comment by MyWay** [comment]
It seems it has been solved.

**Comment by prawnsalad** [comment]
@ircer are you still seeing these issues?
