### ISSUE TITLE
Consider a more permissive license

### ISSUE THREAD

**Issue by anshin** [prawnsalad/KiwiIRC#683]
I'm currently considering how to use Kiwi as a chat for a website, so I'd like to modify it to automatically authenticate users using NickServ.

But, because Kiwi is copyleft, I can't simply use a secret salt and the users' password hashes as NickServ passwords. I'm sure there are also other situations where copyleft becomes problematic/requires more work for security reasons, so I figured I would see whether this is something you might consider.

**Comment by prawnsalad** [comment]
There are server-side modules (not yet documented...) and client plugins that will not fall under the license.

However I'm not sure what you're trying to do is the best way to go about it. A few points:
1. If your network supports SASL (most modern ones do) then Kiwi will authenticate with services automatically. No changes needed.
2. Any hashing should be done by services itself, not Kiwi.

**Comment by anshin** [comment]
Thanks, I forgot about server-side modules.

The hashing is in order to mitigate the risk of impersonation in the event of an SQL injection attack—the idea is that I can use an existing authentication method and assign users a generated password for services (specifically, comprised of something like `hash(username, password_hash, registration_date, "my super top secret salt")`.

I'll look into SASL, since I don't thoroughly understand it yet. Thanks.

**Comment by CoryChaplin** [comment]
Depending on your services, you could also make your services run an ldap or
other identification on your existing system.
Would be the good way to do what you want in my opinion.

-- 
Elephantman

De :  anshin <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd51763ff0a6dcdcdf17a54f76ca15abf296e4b585b92cf000000011112f0d79
2a169ce03961911@reply.github.com>
Date :  samedi 7 mars 2015 18:01
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  Re: [KiwiIRC] Consider a more permissive license (#683)
