### ISSUE TITLE
Customize template login

### ISSUE THREAD

**Issue by Chrysweel** [prawnsalad/KiwiIRC#686]
I open this issue, because I think that this doubt is useful and to can have it many people.

I want customize the template login. 

I know some posibilities:
* Modify index.html.tmpl , the template "tmpl_server_select" and customize there.
* Create a applet as the example of documentation ( https://kiwiirc.com/docs/scripting/applets )
* Create a plugin, same code of applet, but in plugin.

My question is...
Can I customize only the template with a plugin ? But... only the template.
I want continue with same code and events of serverselect.js , but only I want change the template and styles css... but from a plugin, without modify internal code kiwi and without to copy and to paste all code. ;)

Is possible ?

thanks in advance

**Comment by prawnsalad** [comment]
The best way for this is either your point 1 or to modify index.html. The page is created from the templates before the plugins are loaded so they cannot modify the template in time.

If your changes are rather simple you could modify the document live from a plugin. Eg.: http://webbnc.snoonet.org/
What I do here to modify that screen from a plugin is just plain jquery: `$('.server_details .have_pass').hide();`
