### ISSUE TITLE
Is it possible to run just the client?

### ISSUE THREAD

**Issue by Rangers51** [prawnsalad/KiwiIRC#691]
For my site, I want to be able to create my own themes to match my site's skins, but I don't want my IRC provider to be required to host those themes because this will make theme maintenance a pain (if they're even willing to host my themes in the first place).

Therefore, I'd like to be able to manage the client on my own site and merely point it at my provider's round robin for connections. Is that possible without also having to configure a server of my own? 

Thanks!

**Comment by prawnsalad** [comment]
You can run the Kiwi server without the IRC server. The Kiwi server serves up the web frontend and deals with the IRC connections to the IRC server, so you can be modifying the themes as much as you like without touching the IRC server.
