### ISSUE TITLE
Feature request: Hard url's to channels

### ISSUE THREAD

**Issue by anubiann00b** [prawnsalad/KiwiIRC#697]
For example, https://kiwiirc.com/client/example should take me to the channel #example.

**Comment by spartakode** [comment]
@anubiann00b any ideas for how you would specify the other options such as server, port, nick, and ssl?

**Comment by anubiann00b** [comment]
`?nick=anubiann00b&server=freenode&port=23` possibly?

Well the whole thing could be like that actually...

` https://kiwiirc.com/client/?nick=anubiann00b&channel=example`

**Comment by M2Ys4U** [comment]
This feature already exists.

For example: https://kiwiirc.com/client/irc.freenode.org:+6697/KiwiIRC?nick=kiwi_user? will connect you to Freenode over TLS and join #KiwiIRC with the nick kiwi_user followed by some random digits.

**Comment by prawnsalad** [comment]
Just to add to this, channels can either be specified after the server address as @M2Ys4U example shows, or after the whole URL such as: https://kiwiirc.com/client/irc.freenode.org/#channel1,#channel2
