### ISSUE TITLE
IOs virtual keyboard

### ISSUE THREAD

**Issue by H7-25** [prawnsalad/KiwiIRC#704]
Using development branch, one time the virtual keyboard is opened , there's no way to make it disappear. Tested on iphone 5 ios 8.3.

**Comment by H7-25** [comment]
The bug look be related to autocomplete feature, commenting line 20 in controlbox.js make it work 
//this.bindAutocomplete();

**Comment by prawnsalad** [comment]
I've just fixed a bug that relates to focusing elements with the autocomplete UI enabled. https://github.com/prawnsalad/KiwiIRC/commit/925d323a36172f994ce34065faa03ef02a0724e8

Does this solve the issue you're seeing?

**Comment by prawnsalad** [comment]
Tested this on IOS and no longer duplicate this issue. Please re-open if you still have the same issue.
