### ISSUE TITLE
KiwiIRC on RedHat OpenShift. Timed out

### ISSUE THREAD

**Issue by ypopovych** [prawnsalad/KiwiIRC#706]
I tried to setup KiwiIRC on Openshift.
Server started, but can't connect to IRCd server.

First it show "EACCESS bind" exception.
I changed config to this
conf.outgoing_address = {
    IPv4:  process.env.OPENSHIFT_DIY_IP || "0.0.0.0"
    //IPv6: '::'
}; 

And it timed out. What I need provide for outgoing address?

**Comment by IICUX** [comment]
Fixed by editing sources of server/irc/connection.js
Commented "localAddress:" strings and connection start working.

**Comment by prawnsalad** [comment]
The outgoing address should have always stayed as the default "0.0.0.0". Did that not work in the first place?
