### ISSUE TITLE
Ghosted nicks

### ISSUE THREAD

**Issue by MaksimKneller** [prawnsalad/KiwiIRC#708]
I installed a standalone KiwiIRC on my server. Often when a user disconnects and reconnects thir nick remains on the IRC server as a ghost and Kiwi adds 01 to their new nick. I have to restart the KiwiIRC process on my server to clear this caching. It appears that even if the browser disconnects, Kiwi keeps the connection alive. Is there a way around this?

**Comment by rubinlinux** [comment]
I have had reports of this happening to my kiwiirc install too.
