### ISSUE TITLE
Is poeditor.com used?

### ISSUE THREAD

**Issue by mlocati** [prawnsalad/KiwiIRC#719]
I translate KiwiIRC in Italian at https://poeditor.com/projects/po_edit?id_language=75&id=7719

BTW, I see that https://github.com/prawnsalad/KiwiIRC/blob/master/client/src/translations/it.po is not synchronized with the translations of poeditor.com.

So, how/where should I translate KiwiIRC?

**Comment by prawnsalad** [comment]
Yes, poeditor.com is used.The translations were updated on the development branch, https://github.com/prawnsalad/KiwiIRC/tree/development/client/src/translations

When a new release is ready then the master branch is updated.

**Comment by mlocati** [comment]
Sorry, I didn't noticed this.
What about making the development branch the default one?

**Comment by prawnsalad** [comment]
The main reason for not updating the master all the time is so that when people are installing kiwiirc they are installing a stable version by default and not a development unstable version.

There is a note for the development branch in the readme for people looking for development.
