### ISSUE TITLE
Can't send client's ip with local server address

### ISSUE THREAD

**Issue by dateno1** [prawnsalad/KiwiIRC#720]
when i input irc server address to web domain or localhost kiwi can send client's ip address to ircd

but it not work with 'local domain'

server address example : 
localhost (ok)
irc.test.com (1.2.3.4) (ok)
irc.local.test (192.168.100.200) (not work)

when i using 'local domain' it send server's netbios name to ircd instead client's ip address

**Comment by prawnsalad** [comment]
I don't think I understand what you're saying. What's 'local domain'?

**Comment by dateno1** [comment]
for working on local network (use private network ip range)

example : 192.168.*.*/10.*.*.*

i was tested C class type (192.168.*.*) (kiwi server and ircd server is not same)

it send kiwi server's netbios name instead client's ip address

**Comment by prawnsalad** [comment]
This is because kiwiirc does a reverse lookup of the clients IP address. If it resolves to something and matches the IP, kiwiirc will send that to the IRCd. This is expected behaviour.
