### ISSUE TITLE
Switching chat tabs inside kiwiirc does not set unread line marker at the bottom

### ISSUE THREAD

**Issue by FourSword** [prawnsalad/KiwiIRC#721]
Currently when having multiple chat tabs open in kiwiirc the unread line marker does not switch to the bottom when changing chat tabs.
Only by changing browser tabs or switching focus to another application sets the unread line marker to the bottom.

To reproduce: Have at least 2 chat tabs open and switch between them while new messages are posted, the unread line marker position will not change.

If this is not a desirable feature, is it possible to add a shortkey or an option in the settings?
I currently have a workaround for this problem by switching focus to another application for every chat where new messages are posted.

**Comment by prawnsalad** [comment]
This has now been implemented correctly in the development branch - due into the next minor kiwi release any time now. Thanks!
