### ISSUE TITLE
Is it possible to generate a widget to embed in a website using my own server?

### ISSUE THREAD

**Issue by rgsuarez** [prawnsalad/KiwiIRC#722]
Is it possible to generate a widget to embed in a website using my own server? Basically I want to create a widget that is run from my own server instead of the one on the KiwiIRC site.

I tried simply replacing the portion of the URL from the widget generator on the KiwiIRC site with my URL information but that did not work.

Any suggestions?

**Comment by prawnsalad** [comment]
You use the exact same URL structure but with whatever settings you have. kiwiirc.com uses /client/ instead of the default /kiwi/, maybe that's where your URL isn't working. This can be changed in your config.js if needed.
