### ISSUE TITLE
Save nickname

### ISSUE THREAD

**Issue by michaelforge** [prawnsalad/KiwiIRC#724]
Is it possible to save nickname, filled in last session?

**Comment by prawnsalad** [comment]
This is best done in a client plugin. https://kiwiirc.com/docs/scripting/client_plugins

On kiwiirc.com I use the following:
~~~~~
kiwi.plugins.on('loaded', function() {
    if ($('#kiwi .server_details input.nick').val() === '') {
        if(kiwi.settings.get('previous_nick')) {
            $('#kiwi .server_details input.nick').val(kiwi.settings.get('previous_nick'));
        }
    }


    var gateway = kiwi.components.Network();
    gateway.on('connecting', function(){
        kiwi.settings.set('previous_nick', $('#kiwi .server_details input.nick').val());
        kiwi.settings.save();
    });
}

~~~~~

**Comment by michaelforge** [comment]
Thanks for this snippet!
Strange, our instance never reaching the state `gateway.on('connecting'`, so it's never saving it.

![2015-07-03_22-17-56](https://cloud.githubusercontent.com/assets/904839/8503984/73110fc4-21d1-11e5-9514-29cf0ef7dff5.png)

Actually my nickname currently is not saving on kiwiirc.com too. It's just not appearing in browser's local storage.

**Comment by michaelforge** [comment]
@prawnsalad 
Could you check this? :o

**Comment by prawnsalad** [comment]
Ah sorry, try the `connect` event instead of `connecting`.

**Comment by michaelforge** [comment]
@prawnsalad 
OK! Now settings are saving on client's browser,
but `previous_nick` is always empty:
![2015-07-27_23-43-51](https://cloud.githubusercontent.com/assets/904839/8917281/c839f8ee-34b9-11e5-849b-4787367a7909.png)

Why could it be so?
We're randomising nickname on enter, like guest_89153, but KIwiIRC not remembering both random nickname or typed by hand.

**Comment by michaelforge** [comment]
Sorry for reopening, but still can't find a way to save a nickname.. :sweat: 
I tried your snippet, but it results in 'previous_nick" being always empty.

We use random nicknames like guest8913 in KiwiIRC options + your snipper up there. Nickname is not being saved.

If you have a moment, maybe you could point to something?
https://irc.free-ro.com/
