### ISSUE TITLE
Generate random user_id of a configurable length and store this in a cookie

### ISSUE THREAD

**Issue by Robby-** [prawnsalad/KiwiIRC#730]
It would be nice if KiwiIRC could add a feature where the user_id is generated randomly, consisting of lowercase letters `a-z` and numbers `0-9`, and of a configurable length, and then store this value in a cookie, and use this value for subsequent visits to the chat. This would help to ban users who don't clear cookies but do change IP addresses often (either deliberately or not) in such a way that we can put bans on that value instead.
An example of such a generated random user_id string with a length of 9 would be `hoh7mei8j`.
Configurable because IRC networks allow various lengths for the username/ident field.

The expiration time of this cookie being also configurable would probably not be a bad idea either. Resetting the expiration time on every visit.

I'm aware there may be privacy concerns with this feature, but in my opinion this should be up to the IRC networks using KiwiIRC to decide whether to enable or disable this feature for their IRC network. Its already tough enough to keep certain abusive users out due to how IRC works (as explained above), so this would be a welcome addition.

**Comment by CoryChaplin** [comment]
Hi,

I¹ve got a plugin+module that does that here :
https://github.com/CoryChaplin/KiwiIRC/blob/europnet/client/assets/plugins/u
sername.html 
https://github.com/CoryChaplin/KiwiIRC/blob/europnet/server_modules/username
.js 

-- 
Elephantman

De :  Robby <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd501d3f4e5683a30d9bb0b071c8640b0264d80a7b292cf0000000111c4077b9
2a169ce05b848bc@reply.github.com>
Date :  lundi 20 juillet 2015 02:48
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [KiwiIRC] Generate random user_id of a configurable length and
store this in a cookie (#730)

**Comment by Robby-** [comment]
Hello, I've tried this and it doesn't seem to work, the login page then gets stuck in and endless reload-loop forcing me to kill the kiwiirc process.

I added this to config.js:
```
conf.client_plugins = [
    "/kiwi/plugins/username.html"
];
```

I'm on the development branch as that is what your `europnet` branch seems to be based on.

**Comment by CoryChaplin** [comment]
You¹ll also need the server module.

-- 
Elephantman

De :  Robby <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5cb4063b79b6a0ce16e24637673a09853c70ba9ce92cf0000000111ce36f09
2a169ce05b848bc@reply.github.com>
Date :  lundi 27 juillet 2015 20:14
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Cc :  Cory CHAPLIN <elephantman@europnet.org>
Objet :  Re: [KiwiIRC] Generate random user_id of a configurable length and
store this in a cookie (#730)

**Comment by Robby-** [comment]
I have put both files in the folders they need to be in, `username.js` in `server_modules/`, and `username.html` in `client/assets/plugins/`.

**Comment by Robby-** [comment]
Is there maybe something else that I need to do? Some undocumented settings that need to be added to config.js?

**Comment by Robby-** [comment]
It seems I have overlooked the `conf.modules = [];` setting completely, but I still have no idea what to put in there as there is lack of good documentation. I tried `conf.modules = [ "username.js" ];` and `conf.modules = [ "username" ];`, but the endless reload-loop still occurs.

**Comment by CoryChaplin** [comment]
Does your kiwi work without this module ?

-- 
Elephantman

De :  Robby <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5f9d2de832e4e7e0f857aa72c7021c04e8df17d6f92cf0000000111ce4e3e9
2a169ce05b848bc@reply.github.com>
Date :  lundi 27 juillet 2015 21:53
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Cc :  Cory CHAPLIN <elephantman@europnet.org>
Objet :  Re: [KiwiIRC] Generate random user_id of a configurable length and
store this in a cookie (#730)

**Comment by Robby-** [comment]
Yes.

**Comment by CoryChaplin** [comment]
Well, dont know, works well for me.
Anything in the console ?

-- 
Elephantman

De :  Robby <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd59baa7a6f6fb426e024bb2c2c4872c327f86e765092cf0000000111ce4f099
2a169ce05b848bc@reply.github.com>
Date :  lundi 27 juillet 2015 21:56
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Cc :  Cory CHAPLIN <elephantman@europnet.org>
Objet :  Re: [KiwiIRC] Generate random user_id of a configurable length and
store this in a cookie (#730)

**Comment by Robby-** [comment]
Nothing useful, except a confirmation that username.js was successfuly loaded:
```
./kiwi -f start
info: Module username.js loaded successfully
info: Listening on 127.0.0.1:7778 without SSL
```
That is all.

**Comment by prawnsalad** [comment]
There is nothing in that server module that would be causing a browser redirect. Does `http://yourkiwiserver.com/kiwi/plugins/username.html` load OK in your browser? Should it not be set to `/kiwi/assets/plugins/username.html`?

Side note for server plugins - they're not documented at all yet as they can be expected to change very soon. They're currently experimental so please keep an eye out for warnings when you update kiwi in future.

**Comment by Robby-** [comment]
Inserting `/assets/` in the path fixed it, thanks!

`http://yourkiwiserver.com/kiwi/plugins/username.html` shows me the login page, but you probably meant `http://yourkiwiserver.com/kiwi/assets/plugins/username.html`, which does show me a blank page and viewing the source code confirms it loaded fine. Thanks again.

**Comment by prawnsalad** [comment]
Awesome, enjoy!

**Comment by suBDavis** [comment]
Just wanted to leave a comment and say that this appears to still be an issue. I tried to load an empty plugin (no code in my script tags) and also got the infinite loop.  Robby's solution worked for me, but the documentation should be changed.  

Thanks

**Comment by prawnsalad** [comment]
@suBDavis the loop was caused by using an incorrect plugin URL. Which part of the docs should be changed?

**Comment by Robby-** [comment]
He probably means [this](https://kiwiirc.com/docs/scripting/client_plugins) page, the `Structure of a client plugin` section seems to contain wrong paths, it's missing the `/assets` part in them.

The same goes for the `conf.client_plugins` setting in the `config.example.js` file. This reminds me, why is the example of that setting using a full URL as default? I use relative paths like `/kiwi/assets/plugins/myplugin.html` instead, works fine and is better in cases where the URL can change. I can see a use case where someone wants to load remote plugins, but who really does that. Maybe provide 2 examples, one with a full `http://` URL and one with a relative path?
