### ISSUE TITLE
daemonize2 issue

### ISSUE THREAD

**Issue by KeiroD** [prawnsalad/KiwiIRC#740]
Hi,

`npm install` presents me with the following:

`npm WARN package.json daemonize2@0.4.2 No repository field.`

`npm list` presents the following:

kiwiirc@0.9.1 /home/derp/KiwiIRC
├── daemonize2@0.4.2
├─┬ engine.io@1.5.2
│ ├── base64id@0.1.0
│ ├─┬ debug@1.0.3
│ │ └── ms@0.6.2
│ ├─┬ engine.io-parser@1.2.1
│ │ ├── after@0.8.1
│ │ ├── arraybuffer.slice@0.0.6
│ │ ├── base64-arraybuffer@0.1.2
│ │ ├── blob@0.0.2
│ │ ├─┬ has-binary@0.1.5
│ │ │ └── isarray@0.0.1
│ │ └── utf8@2.0.0
│ └─┬ ws@0.7.2
│   ├── options@0.0.6
│   └── ultron@1.0.2
├── es6-promise@1.0.0
├── eventemitter2@0.4.14
├── iconv-lite@0.4.4
├── ipaddr.js@0.1.3
├── lodash@2.4.1
├── negotiator@0.4.3
├─┬ node-static@0.7.4
│ ├── colors@1.1.2
│ ├── mime@1.3.4
│ └─┬ optimist@0.6.1
│   ├── minimist@0.0.10
│   └── wordwrap@0.0.3
├─┬ po2json@0.3.0
│ ├─┬ gettext-parser@0.2.0
│ │ └── encoding@0.1.11
│ └─┬ nomnom@1.5.2
│   ├── colors@0.5.1
│   └── underscore@1.1.7
├─┬ socksjs@0.4.4
│ └── ipaddr.js@0.1.2
├── spdy@1.19.1
├─┬ uglify-js@2.4.12
│ ├── async@0.2.10
│ ├─┬ optimist@0.3.7
│ │ └── wordwrap@0.0.3
│ ├─┬ source-map@0.1.43
│ │ └── amdefine@1.0.0
│ └── uglify-to-browserify@1.0.2
└─┬ winston@0.7.3
  ├── async@0.2.10
  ├── colors@0.6.2
  ├── cycle@1.0.3
  ├── eyes@0.1.8
  ├── pkginfo@0.3.0
  ├─┬ request@2.16.6
  │ ├── aws-sign@0.2.0
  │ ├── cookie-jar@0.2.0
  │ ├── forever-agent@0.2.0
  │ ├─┬ form-data@0.0.10
  │ │ └─┬ combined-stream@0.0.7
  │ │   └── delayed-stream@0.0.5
  │ ├─┬ hawk@0.10.2
  │ │ ├── boom@0.3.8
  │ │ ├── cryptiles@0.1.3
  │ │ ├── hoek@0.7.6
  │ │ └── sntp@0.1.4
  │ ├── json-stringify-safe@3.0.0
  │ ├── mime@1.2.11
  │ ├── node-uuid@1.4.3
  │ ├── oauth-sign@0.2.0
  │ ├── qs@0.5.6
  │ └── tunnel-agent@0.2.0
  └── stack-trace@0.0.9

How do fix? Google is not helpful with this.

**Comment by prawnsalad** [comment]
It is only a warning to show that daemonize2 is missing some information. It is not an error and will work without issue.
