### ISSUE TITLE
Error 2015-08-21 01:01:45 - warn: irc_connection error (zeus.*****.net): code=EPIPE, errno=EPIPE,

### ISSUE THREAD

**Issue by sikro94** [prawnsalad/KiwiIRC#741]
Hello,
I have Unrealircd & Kiwi IRC on the same server
Sometimes I can't connect the IRC with Kiwi IRC and the logs returns:

2015-08-21 01:01:45 - warn: irc_connection error (zeus.*****.net): code=EPIPE, errno=EPIPE, syscall=write

And sometimes: Erreur de connexion. (Closing Link: anonymous_92147[ip-of-my-server] (Too many connections from your IP)) 

Info: I have Anope

Someone knows why ?

Thank you

**Comment by M2Ys4U** [comment]
I have just replied to you on the mailing list. Here is what I wrote:

>It looks like unreal is configured to only allow a certain number of
connections from a single IP address.

> All users, no matter where they connect from, will appear to unreal as
if they are coming from the server where kiwi is installed.

> You could try setting up a [WEBIRC](https://kiwiirc.com/docs/webirc) configuration line in your
unreal config or increasing the limit on connections from a
single IP address.

**Comment by M2Ys4U** [comment]
Confirmed as fixed on the mailing list.

**Comment by pedro-nonfree** [comment]
@M2Ys4U I tried to find the solution in mailing list, but failed retrieving it. Can you post the fix here? Thanks

**Comment by prawnsalad** [comment]
@pedro-nonfree this veresion of KiwiIC has not been supported for some time. You should take a look at https://github.com/kiwiirc/kiwiirc

You should also look into your IRC servers documentation for WEBIRC to fix this issue.
