### ISSUE TITLE
NickServ identification option

### ISSUE THREAD

**Issue by AGausmann** [prawnsalad/KiwiIRC#743]
I am currently hosting an IRC server for a [Minecraft community](http://openredstone.org). The staff team is wanting to require users to register their nicknames with NickServ; however one of the downfalls is that Kiwi IRC does not have support. We are currently using Kiwi IRC embedded in our website, and if we restrict our channel to registered users only, the channel auto-join function would fail because the user has not registered/identified yet. It would be nice to provide NickServ authentication as an alternative instead of the IRC standard PASS command (which our server does not support).

**Comment by M2Ys4U** [comment]
If your server (and services) supports SASL then when the user enters their password on the connection screen it should authenticate them to services.

**Comment by AGausmann** [comment]
As you mention that, I forgot to define some things. I'm using ngircd 22-2 and atheme services 7.2.6. I just researched SASL with ngircd and it seems to be supported; however, I can't seem to find the configuration options for it.

**Comment by AGausmann** [comment]
I've switched to inspIRCd and set up PASS forwarding; it seems to work now. Unless this feature should still be considered, it can be closed.
