### ISSUE TITLE
neverending connection

### ISSUE THREAD

**Issue by tykayn** [prawnsalad/KiwiIRC#746]
i setup my own kiwi at http://www.tykayn.net/kiwi/
but when i want to connect, it never ends.

the js console reports this error:
 http://www.tykayn.net/kiwi/transport/?EIO=3&transport=polling&t=1440924933752-5 404 (Not Found)

master branch / setup ubuntu server 14

**Comment by prawnsalad** [comment]
That isn't setup correctly. Kiwi IRC has its own built in web server as it needs to handle outgoing IRC connections. Take a look through the readme for installation instructions: https://github.com/prawnsalad/KiwiIRC/blob/master/README.md

I'm going to close this thread as it isn't a bug with Kiwi, but if you do need more help setting it up there is the mailing list here: https://groups.google.com/d/forum/kiwiirc
