### ISSUE TITLE
warn: irc_connection error (zeus.*****.lol): code=EPIPE, errno=EPIPE, syscall=write

### ISSUE THREAD

**Issue by sikro94** [prawnsalad/KiwiIRC#751]
Hello,

Someone know what is this error ?
2015-09-04 02:53:46 - warn: irc_connection error (zeus.*****.lol): code=EPIPE, errno=EPIPE, syscall=write

WEBIRC is enabled & auto connect plugin https://kiwiirc.com/docs/scripting/client_plugins too

I can connect the server with mIRC when this error is displayed

**Comment by prawnsalad** [comment]
This just means that kiwi tried sending something to the IRC server after the connection was closed. This is now handled correctly in the development branch.
