### ISSUE TITLE
channel field gets double hash ("##") when irc:// URI includes hash with channel name

### ISSUE THREAD

**Issue by phoithaeff** [prawnsalad/KiwiIRC#753]
When KiwiIRC is installed as irc:// protocol handler in browser, clicking on a link such as follows:
irc://irc.freenode.net/#kiwiirc-default

results in the "Channel" field being filled with two hash symbols.

**Comment by strk** [comment]
confirmed, see #843 for more references

**Comment by prawnsalad** [comment]
This is now fixed in the development branch, working as per the wikipedia article linked in #847. This should be live on kiwiirc.com later this week.
