### ISSUE TITLE
Giving each member a class value of "mode " and the prefix is bad.

### ISSUE THREAD

**Issue by MDTech-us-MAN** [prawnsalad/KiwiIRC#754]
Hello,

I noticed that in the nick list that first of all, each member has (for example) "mode o" as their class. This however means that the browser will see it as 2 classes ("mode" and "o") which is not as one may expect (it also would mean a SINGLE CHARACTER class name, which is considered "terrible practice"). I suggest that it would be best to give each member a general class ("member"?) and a prefix-related class ("member-o"?). Perhaps even the icon part should get its own classes as well. I would guess "icon" for all and "icon-o".

NOTE: I am using the "o" prefix just as an example.

Maxwell.

**Comment by prawnsalad** [comment]
Now changed in the v1.0 branch
