### ISSUE TITLE
Strange hostname (ipv6-only users?)

### ISSUE THREAD

**Issue by MyWay** [prawnsalad/KiwiIRC#759]
I'm getting users with 2606, or things like that as hostname. Can you fix it, please?

**Comment by prawnsalad** [comment]
Is this when using a reverse proxy?

**Comment by MyWay** [comment]
I'm using a nginx reverse proxy, but I don't know if it's happening only when using a reverse proxy, why?

**Comment by MyWay** [comment]
So the problem is at line 180 of server/weblistener.js, address = (address || '').split(':')[0];

**Comment by prawnsalad** [comment]
This is now fixed in https://github.com/prawnsalad/KiwiIRC/commit/618cfd46a8512fd8bb367435dfb8601ceefeec02
