### ISSUE TITLE
Custom highlights unavailable in Chrome extension

### ISSUE THREAD

**Issue by niedzielski** [prawnsalad/KiwiIRC#760]
The custom highlight textbox is not available in the Chrome extension, v0.5.4. Here's a screenshot from v0.9.1 just running from the repo with `./kiwi start` showing the textbox:
![2015-09-21-08-28-37-776825342](https://cloud.githubusercontent.com/assets/1071806/9994510/db35a734-603a-11e5-873b-def3b8e696b3.png)

**Comment by prawnsalad** [comment]
The chrome extension is using the latest stable version (master branch), while the custom highlight option are still in the development branch.

There should be a new release any time now that will see the extension + kiwiirc.com/client updated though.
