### ISSUE TITLE
/names on a channel retrieve nicknames from some other channel

### ISSUE THREAD

**Issue by leofiore** [prawnsalad/KiwiIRC#761]
Step to reproduce:

1. use kiwiirc.com to connect on freenode (https://kiwiirc.com/client/irc.freenode.net)
2. `/join` an empty channel (e.g. `/join ##ohmytest`) (dunno if it happens with non empty channels, for now ensure channel is empty)
3. type `/names` on the input line and press ENTER
4. users column on the right now is filled with unknown people

i suppose is not an easter egg?

**Comment by prawnsalad** [comment]
Nope, no easter egg. Because no channel was specified with /names it was getting a bunch of users from anywhere on the network. It now defaults to the active channel if one is not specified.
