### ISSUE TITLE
Spelling error in the Language Drop Down Menu in Settings - "russian" should be corrected to "Russian"

### ISSUE THREAD

**Issue by annasilchenko** [prawnsalad/KiwiIRC#763]
Typo or spelling error in the Language Drop Down Menu under the Settings tab - "russian" ("русский") should be corrected to "Russian" ("Русский").

Please see screen shot attached. Thanks!

![screenshot](https://cloud.githubusercontent.com/assets/14639243/10084629/7aecf37e-62d2-11e5-9f76-a5f118475b0a.png)

**Comment by prawnsalad** [comment]
Now updated in the development branch - soon to be in master and live. Thanks!
