### ISSUE TITLE
Black theme in Kiwi IRC creates problems with the incoming text

### ISSUE THREAD

**Issue by AntreasAntoniou** [prawnsalad/KiwiIRC#765]
At random intervals I will get weird added tabs at the front of the incoming text chats when using the black theme. E.g.

\tUsername: Hello
\t\t\t     Username: Hello
\t\t\t\t             Username:Hello

I have noticed that it will go away after 15-30 minutes or if I flash my cache. What could be the issue here?

**Comment by prawnsalad** [comment]
Themes don't change the way anything works, so the issue should be the same in all themes?

When you say the tabs will go away after 15-30 mins, is that while you're sat there and they just random disappear or just stop appearing in new messages? 

And also, could you please attach a screenshot here with how you're seeing these tabs? I'm having a hard time imagining this

**Comment by AntreasAntoniou** [comment]
Actually I have tested all the other themes, and only the black theme (my favourite) created this issue. Here is an image.

![dafuq](https://cloud.githubusercontent.com/assets/10792502/10278748/bfc2c068-6b57-11e5-9556-144772a32c17.png)

**Comment by prawnsalad** [comment]
Ah gotcha. That's relating to the sizes of some if the nicks I think.. will look into that!

**Comment by AntreasAntoniou** [comment]
I don't know whether it will help, but I found that if I increase the number of lines that can be stored in the cache the bug becomes rarer, as if it works as some sort of frequency handle. But that's probably because it can store more names before it starts to delete stuff. And maybe that's where the problem is ?

**Comment by prawnsalad** [comment]
Just looking into this to get it fixed, turns out I can't reproduce the issue here. What browser are you using and what URL? The theme you're seeing there is not the one available on kiwiirc.com..

**Comment by AntreasAntoniou** [comment]
Hello there,

The theme being used is the CLI theme from the settings menu, normally the text size is bigger but when the issue occurs the text size changes and the allignment goes out of whack. I am using Chrome on Windows 10. Also I have tested on other browsers such as Microsoft Edge and Mozzila and everything works fine. In fact Chrome also works but breaks at least once every day and I have to delete the cache and fully restart the browser and any open tabs.
