### ISSUE TITLE
Ask user to add KiwiIRC as an application for IRC links

### ISSUE THREAD

**Issue by GreenLunar** [prawnsalad/KiwiIRC#766]
Use this code
```
<script type="text/javascript">
	navigator.registerProtocolHandler("irc", "https://hostname/%s", "KiwiIRC");
</script>
```

See
http://www.lookout.net/test/handler/
http://www.lookout.net/2012/01/testing-registerprotocolhandler-and-web.html
https://html.spec.whatwg.org/multipage/webappapis.html#dom-navigator-registerprotocolhandler

**Comment by prawnsalad** [comment]
You can find this already in the Kiwi client settings (click the cogs in the top right)
