### ISSUE TITLE
Random disconnections every 45 minutes or so

### ISSUE THREAD

**Issue by ghost** [prawnsalad/KiwiIRC#767]
It's been happening a thousand times now, I'm sick of this!

I'm on Freenode, by the way, if that matters.

**Comment by niedzielski** [comment]
I seem to be having a similar issue. Here are the details:
- The issue occurs every few hours.
- I've seen it for the past couple weeks or so at least. I confirm it happens on bee18b6 (development HEAD).
- There is no UI cue that I've been disconnected. On the contrary, I will send messages but they're never received. The only hint is that high activity channels ceases to receive messages.
- Only tested and seen on firrre ZNC and Freenode directly.
- This wasn't an issue with the Chromium / Chrome extension which I believe is quite a few commits back. Also not seen on other clients such as WeeChat and Shout.
- Fixed by reloading my browser (Chromium) tab. I'll try to restart the server from the command line next time.

**Comment by niedzielski** [comment]
I've moved my issue, which seems to be different, over to #773.

**Comment by thenoncoder** [comment]
Well I'm still having my issue.

Every 45 minutes or an hour it randomly disconnects and asks me for a different username, and then repeats.

**Comment by prawnsalad** [comment]
@thenoncoder Do you see any errors appearing in your browser console when it happens? I can't replicate this issue on multiple machines and even a mobile connection.

**Comment by thenoncoder** [comment]
I haven't checked the console, but I don't think that it would show any errors anyways.

Basically, when it does disconnect, it goes "attempting to reconnect in 16 32 64, etc seconds" and eventually asks me for a new nickname, and then does this every 45 minutes or an hour or so.

**Comment by prawnsalad** [comment]
If you could check the console just in case, that would be great. I'm clutching at straws here since I've got nothing else to go on.

Just to confirm, you are using kiwiirc.com/client? And what browser?

**Comment by thenoncoder** [comment]
Firefox 42.0.2 on Windows 10.

**Comment by thenoncoder** [comment]
@prawnsalad this is the console log :

There's a kiwi in your console jquery-1.11.1.min.js line 2 > eval:212:13
_kiwi.gateway.socket.on('open') kiwi.min.js:1:16599
_kiwi.gateway.socket.on('connect') Object { cid: "c23", attributes: Object, _changing: false, _previousAttributes: Object, changed: Object, _pending: false, gateway: Object, _events: Object, panels: Object, collection: Object } kiwi.min.js:1:17640
_kiwi.gateway.socket.on('error') Object { reason: Error } kiwi.min.js:1:16164
_kiwi.gateway.socket.on('reconnecting') kiwi.min.js:1:17032
_kiwi.gateway.socket.on('close') kiwi.min.js:1:16940
_kiwi.gateway.socket.on('reconnecting') kiwi.min.js:1:17032
_kiwi.gateway.socket.on('error') Object { reason: Error } kiwi.min.js:1:16164
_kiwi.gateway.socket.on('close') kiwi.min.js:1:16940
_kiwi.gateway.socket.on('reconnecting') kiwi.min.js:1:17032
_kiwi.gateway.socket.on('error') Object { reason: Error } kiwi.min.js:1:16164
_kiwi.gateway.socket.on('close') kiwi.min.js:1:16940
_kiwi.gateway.socket.on('open') kiwi.min.js:1:16599

**Comment by karai17** [comment]
I believe I have a similar issue to this. KiwiIRC seems to disconnect after a period of inactivity. There seems to be no option to keep the service alive...

**Comment by prawnsalad** [comment]
@karai17 could you try the new version at https://kiwiirc.com/nextclient/irc.server.org/#channel ? See if that disconnects too.

**Comment by karai17** [comment]
that's what i've been using.

**Comment by prawnsalad** [comment]
@karai17 this is the wrong issue tracker and unrelated then. Could you create an issue at the below link that includes the last message you see when you get disconnected and any messages that show up in the browser console when you get disconnected?

https://github.com/kiwiirc/kiwiirc/issues
