### ISSUE TITLE
how to set channel by url query_string

### ISSUE THREAD

**Issue by sjdy521** [prawnsalad/KiwiIRC#772]
Is it possible to set channel info from query string instead of configuration? for example:
`https://kiwiirc.com/client/?channel=#kiwiirc,#test`
if I open this url, I would like to see the `Channel` input box filled with the value of "#kiwiirc,#test"
I want to have this feature to share my different irc address to different friends

**Comment by Chrysweel** [comment]
Hello @sjdy521 , you can do it with a plugin.

I think something like that:

```
            var channels_str = getQueryVariable('channel');
            if (channels_str) {
                var channels = channels_str.split(',');
                $('.server_select').hide();
                $('#server_select_channel').val(channels.join(','));
            }
```

**Comment by sjdy521** [comment]
@Chrysweel 
thank you very much, I will try this.

**Comment by sjdy521** [comment]
@Chrysweel the code works exactly as I expected,  thanks again.
