### ISSUE TITLE
Client hangs every 3-6 hours

### ISSUE THREAD

**Issue by niedzielski** [prawnsalad/KiwiIRC#773]
I'm experiencing an issue every 3-6 hours or so where the UI is no longer updated as if I'm disconnected. Even if I wait an hour or more, all activity ceases and doesn't fix itself until I reload the browser tab.

Here are the characteristics:
- The issue occurs every few hours.
- I've seen it for the past few weeks or so at least. I confirm it happens on 5086b38 (development HEAD).
- There is no UI cue that I've been disconnected. On the contrary, I will send messages but they're never received. The only hint is that high activity channels ceases to receive messages.
- Only tested and seen on firrre ZNC and Freenode directly.
- This wasn't an issue with the Chromium / Chrome extension which I believe is quite a few commits back. Also not seen on other clients such as WeeChat and Shout.
- Fixed by reloading my browser (Chromium) tab.
- When the issue occurs, I can't close channels by pressing the little X or by typing /part.
- There is nothing in kiwi.log around the time of the issue.

**Comment by prawnsalad** [comment]
When this happens, do you see any errors in your browser console? If you're not seeing anything happen when you click the little X then it's a good sign something is appearing there.

**Comment by niedzielski** [comment]
@prawnsalad hm, so it just happened and I see no errors. I can keep it in this state at least for the next hour. Let me know if I can test anything.

**Comment by niedzielski** [comment]
@prawnsalad after a couple hours of being unresponsive (trying to close a tab or change my nick does nothing), it's suddenly working again with no further interactions. Nothing new in the console.

**Comment by prawnsalad** [comment]
@niedzielski Could you try this on the kiwiirc.com/client instance and see if you have the same issues? I'm having a hard time replicating or figuring out where to even go with this issue.

**Comment by niedzielski** [comment]
@prawnsalad, I now think this is purely a connection issue. I discovered my USB Ethernet adapter is a bit flaky on Linux. It resets a few times a day which might cause my machine to fallback to Wi-Fi momentarily. Even though all my other program connections come back, Kiwi does not and there's no visual indicator of this. So, I think, the bug is that Kiwi doesn't always reconnect on connection failure. With this in mind, is it helpful if I try to repro on kiwiirc.com/client or is there additional information I can provide? The only other hint I have at the moment is the note about the Shout IRC client in my previous comment.

**Comment by prawnsalad** [comment]
Yes, testing it on kiwiirc.com/client means I know exactly what you're using and how it's working properly. I know this re-connects without issue for many others so hopefully it works for you also. If it doesn't.. then the issue is elsewhere.

If you could just leave it connected in the background throughout the day and see how it goes. Thanks for the testing!

**Comment by niedzielski** [comment]
@prawnsalad, I haven't seen the issue in the past couple days on kiwiirc.com/client. Is it using development head? If you recall, I also wasn't able to repro on the Chromium / Chrome extension which I believe is a number of commits behind.

**Comment by prawnsalad** [comment]
@niedzielski Sorry for a late reply. kiwiirc.com/client was using a few commits back in the development branch. Are you still having these issues now?

**Comment by niedzielski** [comment]
:+1: I've been using kiwiirc.com/client since you mentioned it and noticed the recent updates. I haven't had the issue so I think this is fixed :) Thanks!

**Comment by niedzielski** [comment]
I just saw this issue again. It's the first time it's happened in a couple months. I was on https://kiwiirc.com/client and the client appears to have become detached somewhere between 4:03:56 AM and 4:09:10 AM (mountain) today and never recovered. I'm not sure if this issue is back or if this was just a really rare occurrence. Just wanted to note it here.
