### ISSUE TITLE
Rejoining after an auto-reconnect does not show the "nickname has joined" message

### ISSUE THREAD

**Issue by Robby-** [prawnsalad/KiwiIRC#787]
After being disconnected and KiwiIRC auto-reconnecting and rejoining the channel, the `nickname has joined` message is not shown, only the `Disconnected from the IRC network` message. It may be more user friendly to show a message that they have rejoined the channel. Manually rejoining after being kicked for example, does show the message again.

**Comment by prawnsalad** [comment]
This is now put in place in the development branch. Due to be in the next minor release any day now. Thanks!
