### ISSUE TITLE
Add option to disable autocomplete

### ISSUE THREAD

**Issue by FrostedFlames** [prawnsalad/KiwiIRC#789]
The autocomplete window, while helpful and letting me see commands I may have missed, is annoying me very much - I know how to perform trivial tasks. I don't need to see the full command list, and I'd appreciate if a complete disable of this feature, or, even better, an adjustable level of autocomplete(e.g. Autocomplete nicknames, Autocomplete commands, Autocomplete nothing) was available.

**Comment by prawnsalad** [comment]
This can be disabled it in the settings > messages window.
