### ISSUE TITLE
Perf hit when lots of people re-join after netsplit

### ISSUE THREAD

**Issue by mestaritonttu** [prawnsalad/KiwiIRC#796]
Noticed this while there were constant netsplits a while ago. The interface freezes for several seconds and CPU fan starts screaming.

**Comment by prawnsalad** [comment]
* How many users were in the channels you were in?
* How many channels were you in?
* Which browser were you using?

**Comment by mestaritonttu** [comment]
7 channels, user amounts ranging from 5 to 100 per channel.
Using Firefox.

**Comment by prawnsalad** [comment]
I can't replicate anything with this that causes CPU fans to scream (especially with under 100 users per channel) but there will always be a slight CPU hit when netsplits happen.

I'm going to close this issue though as the next major version of kiwi (V1.0 branch) will be a even more lighter than the current and should have a noticeable effect when netsplits occur.
