### ISSUE TITLE
Listen and detect finish event "whois"

### ISSUE THREAD

**Issue by Chrysweel** [prawnsalad/KiwiIRC#814]
Hello. 

I found an error.. I'll try to explain it ..

I have a plugin, it plugin has code : 
```
     var myFunction = function(response) {
                    console.log(response);
                    .....
                   my code
                   .....
                    //if we are in finish of whois
                    if(response.end ){
                        console.log('endd whois');
                        network.off('whois', myFunction);
                    }
                };

                //check if user is registered in irc
                network.on('whois', myFunction);
               network.raw('whois '+username);
```

It work if I get messages of whois in order correctly, but I get first the last message.
```
end -> true
msg->"End of /WHOIS list."
```
So code execute network.off ... so the plugin does nothing and dont work correctly.

I think that the problem is with the "Transports available to the client."
In my case in mozilla firefox I get the last message of first.

But I just discovered that If I enable option in config kiwii: 
>conf.client_transports = ['polling'];

It work good...

Is very strange any idea ?

**Comment by prawnsalad** [comment]
Hey, did we solve this on IRC? I seem to remember going over it

**Comment by Chrysweel** [comment]
mmm I dont remember @prawnsalad sorry !

I close issue, and If the problem continue I will open in a future ! :)
