### ISSUE TITLE
Displaying real IP upon connection. 

### ISSUE THREAD

**Issue by Az0nic** [prawnsalad/KiwiIRC#815]
Hello, I'm running my own IRC server (irc-ratbox). But I'm having difficulty display users real IP addresses. I've compiled Kiwi and I can connect to it, but when other users try and connect it's displaying the IP address of the box in which it's running from. 

In my config.js settings I've added: 

    conf.webirc_pass = {
    "irc.mydomain.com": "passwordhere",
};

I have added the WEBIRC / CGI:IRC config from your website into my ircd conf, (which works perfectly fine) but I'd prefer for users to connect with their real IP to enforce bans etc. 

In my ircd config is: 

auth {
    user = "cgiirc@109.169.31.4";
    user = "cgiirc@107.161.19.53";
    user = "cgiirc@107.161.19.109";
    password = "passwordhere";
    spoof = "webirc.";
    class = "users";
};

Would this work, or is it for unreal only?

cgiirc {
       type webirc;
       hostname = "YOUR_KIWI_SERVER_IP_ADDRESS";
       password =  "passwordhere";
};

Any help would be greatly appreciated.

**Comment by prawnsalad** [comment]
Hi, did we solve this on IRC?

**Comment by Az0nic** [comment]
No, I can't figure out how to display the real IP address of users connecting to my IRC server.

**Comment by prawnsalad** [comment]
Ok. Well the config you have copied from kiwiirc.com is only for the kiwi server on kiwiirc.com. Since you are using your own kiwi server it is entirely independent.

Where you have these lines in your ircd config: `user = "cgiirc@107.161.19.109";` add another one with the IP of your own server. I would guess you will need to put your external IP here.

**Comment by Az0nic** [comment]
I *think* I know what the problem is, nginx doesn't install http_realip_module by default, so the configuration in config.js can't see IP header = "x-forward-for". 

I'll let you know if I've got it working, I appreciate the help. :-)

**Comment by prawnsalad** [comment]
I'm assuming this issue was resolved now. If not we can re-open this issue

**Comment by Az0nic** [comment]
Hello! I apologise for the very late reply, but I've resolved the issue. So I appreciate your assistance! I've noticed that you can use a plugin which allows file uploads & sharing using the filepicker service? I was wondering if you've got a direct link for that plugin so I could implement it?
