### ISSUE TITLE
/list causes empty window

### ISSUE THREAD

**Issue by cehib** [prawnsalad/KiwiIRC#827]
`/list` causes an empty window to be created. The real channel list is created in the window next to it.

Tested on UnrealIRCd-4.0.1.

![capture](https://cloud.githubusercontent.com/assets/16916976/12611133/1d312e4e-c4e3-11e5-9660-0d2b3a63202a.PNG)

**Comment by cehib** [comment]
@prawnsalad Do you have an ETA on this bug?

**Comment by cehib** [comment]
Will someone fix this bug?

**Comment by prawnsalad** [comment]
Sorry for the late reply.. this is on my todo list for this week. It will effect every registered network on kiwiirc.com as it's part of the searchable channel list feature. Will update this thread once it's completed.

**Comment by cehib** [comment]
@prawnsalad ok

**Comment by prawnsalad** [comment]
This is now fixed on kiwiirc.com. Thanks!

**Comment by cehib** [comment]
@prawnsalad hmm, do you see a strange blinking/wiping behaviour now? I do ..., seems to take some seconds to open the list, and in the meantime some strange things going on quickly.
