### ISSUE TITLE
File upload via Filepicker not working

### ISSUE THREAD

**Issue by anonsubmitter** [prawnsalad/KiwiIRC#832]
When trying to upload a file by clicking on the blue upload icon in the bottom right corner of Kiwi IRC a new window opens saying "Application AisMDMMInTAOji478kuNxz is unavailable.". Could this have something to do with Filepicker turning into Filestack?

**Comment by CoryChaplin** [comment]
Hi,

It looks like Filepicker is now applying the limits to it¹s dev accounts and
is locking those that go above the limit.
I¹ve got that issue on my network and have disabled it for now.

-- 
Elephantman

De :  anonsubmitter <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd513ff587945b786e78c1b5c9274f84c194a97cd5292cf0000000112c8741f9
2a169ce07ca1c1b@reply.github.com>
Date :  mardi 2 février 2016 14:41
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [KiwiIRC] File upload via Filepicker not working (#832)

**Comment by prawnsalad** [comment]
Filepicker has just closed our account for hitting limits as @CoryChaplin mentions. I'm talking to them at the moment to try get something sorted. Will update this issue when I hear something

**Comment by prawnsalad** [comment]
The filepicker plugin is now working again though I'm not sure what their plans are right now. Hopefully it stays this way until I can get a solid plan with them in place.

**Comment by notanewbie** [comment]
I'm getting this error exact error. This occurs on both macOS and Windows 10 when I'm trying to upload files on Freenode channels.

**Comment by jadapitman76** [comment]
How do I move forward if I  don't have this feature avalibale?

**Comment by prawnsalad** [comment]
the file uploading service we use (filestack.com) is very temperamental now so I wouldn't rely on it. You should probably be trying to use the new version of kiwi though which has a much better file upload service, https://kiwiirc.com/nextclient/irc.freenode.net/#kiwiirc
