### ISSUE TITLE
Inspircd +y user mode not displaying user prefix in nicklist

### ISSUE THREAD

**Issue by prawnsalad** [prawnsalad/KiwiIRC#844]
Example: https://kiwiirc.com/client/irc.icqchat.net/#icqchat

**Comment by cehib** [comment]
I saw some talk about this in the IRC channel a few days ago by other users. Is it sorted yet?

**Comment by prawnsalad** [comment]
This is now fixed in the development branch an will most likely be live on kiwiirc.com later this week.

**Comment by cehib** [comment]
@prawnsalad thanks, look forward to seeing it on kiwiirc.com client.

**Comment by cehib** [comment]
@prawnsalad ok, works on some networks but not on others, both using +y and ! prefix

**Comment by cehib** [comment]
can we open this since it isn't fixed

**Comment by prawnsalad** [comment]
It should be the same on all networks if they haven't changed the modes around. Which network doesn't it work on?

**Comment by cehib** [comment]
@prawnsalad example http://www.ukchatrooms.co.uk

**Comment by prawnsalad** [comment]
The webchat on that website is using kiwiirc.com/client which is not yet updated. So it will not be working anywhere as yet. It will be updated this evening.

**Comment by cehib** [comment]
@prawnsalad sorry, ok

**Comment by cehib** [comment]
still not working, not sure whether it's been updated or not yet, just advising

**Comment by cehib** [comment]
@prawnsalad even if i use kiwiirc.com/client it works on irc.icq-chat.com but doesn't work on irc.ukchatrooms.co.uk , both using kiwiirc.com/client and same prefix !

**Comment by prawnsalad** [comment]
@cehib kiwiirc.com is now fully updated. Could you confirm that it's now working no your network? You may need to clear your browsers cache at first

**Comment by cehib** [comment]
@prawnsalad no its not

**Comment by prawnsalad** [comment]
What network and channel can I test this on?

**Comment by cehib** [comment]
@prawnsalad IRC.ukchatrooms.co.uk #Chatroom

**Comment by prawnsalad** [comment]
Ah I see that I missed a stylesheet when updating the live kiwi servers. Should be fine now: ![example](https://i.imgur.com/spjYnsX.png)
