### ISSUE TITLE
Chrome: Autocompleted nicks don't include space after colon

### ISSUE THREAD

**Issue by ulic75** [prawnsalad/KiwiIRC#845]
Test on Chrome 48.0.2564.103 m, Firefox 42, IE11 and Edge, all on Windows 10.

In chrome if a type part of a nick, hit tab, then enter the nick appears with a colon but there is not a space after the colon.  If I inspect the value with jquery $('.inp').val() there indeed is a space, but it's not shown on the UI and if type my message and press enter the message is sent without a space.

Doing the same thing in other three works as I would expect.

I'm not sure how to solve this, it's got to be some sort of chrome input auto-trim or something.  I'll do some more research.

**Comment by prawnsalad** [comment]
This is actually caused by the text-wrapping styling. The space is inserted but not displayed because of the styes on the input box. I'm not sure how to go about fixing that as yet so if anyone has any ideas..

**Comment by ulic75** [comment]
Ah, I didn't even notice that a text area was being used rather than an normal input field.  What is the purpose of that?  Allow for theming to enable multi line input fields?

**Comment by ulic75** [comment]
Just did a little googling, after limited test I found a solution that seems to work in chrome.  Instead of using the white-space css attribute, you can use wrap="off" as an attribute on the textarea itself.  Of course this doesn't allow for theming to work if that was the intent.

**Comment by prawnsalad** [comment]
Good find! That seems to work on chrome just nicely. Do you have the chance to test on IE at all?

**Comment by ulic75** [comment]
So I added wrap="off" to the textarea and removed line 283 from the main style.css file "#kiwi .controlbox .input .inp { white-space: nowrap; }"

That appeared to work in all 4 default themes in Chrome, IE, Edge, Firefox, and Opera on Windows 10.

However I'm still unclear why a textarea is being used instead of an standard input field.  Seems like the textarea is being styled to behave like an input field.  Because if goal is to allow for a multi-line control based on css styling then I don't think this solution will work as the element attribute can't be modified by css.

**Comment by CoryChaplin** [comment]
A textarea allows to write or paste multiline text. That¹s probably the
reason it¹s been done that way.

-- 
Elephantman

De :  ulic75 <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5fa1de8398bb116232d89847d1f76ff772e45728a92cf0000000112df049e9
2a169ce07ee6589@reply.github.com>
Date :  vendredi 19 février 2016 17:28
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  Re: [KiwiIRC] Chrome: Autocompleted nicks don't include space after
colon (#845)

**Comment by prawnsalad** [comment]
As @CoryChaplin says. using a textarea also allow us to have the height auto adjusting if you do paste for than 1 line; Somebody has a PR for this I think.

@ulic75 Do you want to send a PR for this attribute change?

**Comment by ulic75** [comment]
I also text pasting in multi-line text just to make sure that still works and it appears to.
