### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by swantzter** [prawnsalad/KiwiIRC#846]
Add support for a captcha on the connect screen

**Comment by prawnsalad** [comment]
Why would you want to annoy every single person trying to use the website? Are you having an issue with web scrapers logging into IRC?

**Comment by svbeon** [comment]
I'm more thinking of the possibility to enable it for self hosted versions,
for example freenode webchat does have a captcha to prevent the tip of the
iceberg of spammers

lör 13 feb 2016 13:53 Darren <notifications@github.com> skrev:
