### ISSUE TITLE
web client irc:// link urlencoding issue

### ISSUE THREAD

**Issue by eibbiezza** [prawnsalad/KiwiIRC#847]
If I click on the following link:
irc://irc.gnome.org/%23gtk%2B (urlencoded version of irc://irc.gnome.org/#gtk+)

It takes me to:
https://kiwiirc.com/client/irc%3A%2F%2Firc.gnome.org%2F%2523gtk%252B

And then "Channel" gets filled with:
#%23gtk%2B

Instead of:
#gtk+

**Comment by prawnsalad** [comment]
This is now fixed in the development branch and I expect to be live on kiwiirc.com later this week. Thanks!

**Comment by eibbiezza** [comment]
@prawnsalad 
It looks like that commit fixes #753 but not this issue (that a urlencoded channel gets urlencoded again).

**Comment by prawnsalad** [comment]
Ah I've just re-read your original issue here. I've not seen anywhere that URL encodes the channel name separately, do you know anywhere that describes the URI like that?

**Comment by eibbiezza** [comment]
@prawnsalad 

http://www.gtk.org/development.php

`<a href="irc://irc.gnome.org/%23gtk%2B" class="irc">#gtk+</a>`

**Comment by prawnsalad** [comment]
Yea I don't think they have formatted the URL correctly. The browser takes the link and escapes it into the webirc page. it makes no sense to be escaping it twice over each other.

If there's a spec I've missed that allows this weird double escaping then I'll put it in place, otherwise since that's the only page I've ever seen that way I'd go with they need to format it correctly.

**Comment by eibbiezza** [comment]
@prawnsalad 

What do you think is the correct way to format the URL?

Like this?:
irc%3A%2F%2Firc.gnome.org%2F%23gtk%2B

That's not recognized as a valid URL in Firefox

Like this?:
irc://irc.gnome.org%2F%23gtk%2B

The web client leaves the "Channel" blank and fills the "Server" field with "irc.gnome.org%2F%23gtk%2B" in this case

I'm not suggesting that the double encoding is correct. It seems that either Kiwi or Firefox has a bug which is introducing the second level of encoding.

**Comment by prawnsalad** [comment]
The correct format would be one of:
* irc://irc.gnome.org/#gtk+
* irc://irc.gnome.org/gtk+

In both cases, on the development branch of kiwi about to go live Kiwi will connect to the server irc.gnome.org with the channel box filled with #gtk+. The browser automatically encodes the entire URI and appends it to the Kiwi URL when clicked on.

This is also inline with how the wikipedia page linked in #843 describes. https://en.wikipedia.org/wiki/Internet_Relay_Chat#URI_scheme

**Comment by eibbiezza** [comment]
https://www.w3.org/Addressing/draft-mirashi-url-irc-01.txt

In the irc: URL scheme, "unsafe" characters (RFC 1738, Sec 2.2) in <chstring> or <nickstring> must be encoded by a character triplet consisting of the character "%" followed by the two hexadecimal digits (from "0123456789ABCDEF") which form the hexadecimal value of the octet. (The characters "abcdef" may also be used in hexadecimal encodings.)

Further testing shows this is either a Firefox bug or a bug in the Kiwi protocol handler specification.

**Comment by eibbiezza** [comment]
Based upon my reading of https://developer.mozilla.org/en-US/docs/Web-based_protocol_handlers it looks like the bug is on the Firefox side, as it's not urldecoding the anchor href before passing it to be fully urlencoded for the protocol handler. I will report a bug with Mozilla.

**Comment by eibbiezza** [comment]
Reported to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1249637

**Comment by prawnsalad** [comment]
@eibbiezza A quick heads up while you're dealing with that mozilla issue, the double ## bug is now fixed on kiwiirc.com and should work as expected.

Maybe mozilla might be open to the suggestion of adding kiwi as a an irc:// scheme handler as well as mibbit... being open source it would be a nice fit with firefox. Fancy opening an issue there to suggest this?

**Comment by eibbiezza** [comment]
@prawnsalad 
I've noticed that Mozilla prefers to accept suggestions to use third party services from the third party themselves. They have indicated concern, for example, that the third party might not be ready or willing to absorb the increased traffic from Firefox users. They may also have questions for you, or spec compliance requests. I therefore suggest that you be the one to propose inclusion.
