### ISSUE TITLE
Allow server password in kiwiirc.com clients

### ISSUE THREAD

**Issue by ghost** [prawnsalad/KiwiIRC#852]
Allow us to specify a password in the network/client settings so that we can make our IRC server private and just allow KiwiIRC clients.

**Comment by prawnsalad** [comment]
If you're only wanting kiwiirc connections to your IRCd it would be better to make your IRC server listen on 127.0.0.1 and tell kiwiirc to connect there. This way it's not possible for anyone outside of your server to connect to it.

**Comment by cehib** [comment]
Is it possible to just add a box Password in to the admin part of managing kiwiirc.com clients, and then KiwiIRC can send password in background? We use that not local KiwiIRC.

**Comment by cehib** [comment]
@prawnsalad can you consider this?

**Comment by craigfairhurst** [comment]
I would say this is a must.

**Comment by edmund-huber** [comment]
I'm working around this as well.

**Comment by prawnsalad** [comment]
@edmund-huber this version of kiwiirc is no longer in active development, see https://github.com/kiwiirc/kiwiirc for the new version which does now accept a password options.
