### ISSUE TITLE
Embed a url / widget using your own site

### ISSUE THREAD

**Issue by Casey952** [prawnsalad/KiwiIRC#858]
It would be a nice feature to be able to embed a url / widget using your own site when you are running Kiwi IRC on your own box.

Have a config block for the webchat address -- https://your.site:7777 and generate the channel and nick etc using your address.

qwebirc and Iris has a feature Add webchat to your site that has a config base address https://your.site and port number where you generate your channel and nick using your own site https://your.site #channel

**Comment by Casey952** [comment]
perhaps have a list of options when generating the code to generate the code as a url or iframe etc for your channel and nick using your own site

**Comment by spencerthayer** [comment]
This doesn't work?

**Comment by prawnsalad** [comment]
This has been available since day 1, not sure why I didn't see this issue.

yourkiwi.com/#channel
yourkiwi.com/kiwi/irc.server.com/#channel

These work in iframes or URLs
