### ISSUE TITLE
Connecting to multiple channels via URL

### ISSUE THREAD

**Issue by Crayder** [prawnsalad/KiwiIRC#859]
I have two channels I'd like to connect to (examples);

	https://kiwiirc.com/client/irc://irc.tl/channel1
	https://kiwiirc.com/client/irc://irc.tl/channel2

I want to connect to both of these at the same time with just one link.
I've tried a few things like separating them by commas but then I get "Server not found."

I know it used to be possible but I don't remember how, so how do I do this?

Note: I'd prefer to have it with the username too.

**Comment by CoryChaplin** [comment]
Here¹s a sample that does what you want and a bit more :
https://kiwiirc.com/client/irc.freenode.org/channel1,channel2?nick=test&them
e=cli

-- 
Elephantman

De :  Corey Iles <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd581fe77ac94cf20aa206350d89eeba2dd34dd867292cf0000000112fde9739
2a169ce0860cba5@reply.github.com>
Date :  lundi 14 mars 2016 03:52
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [KiwiIRC] Connecting to multiple channels via URL (#859)

**Comment by Crayder** [comment]
Solved.
