### ISSUE TITLE
WebCam

### ISSUE THREAD

**Issue by cirinho** [prawnsalad/KiwiIRC#883]
how to implement webcam support?
example: something like lightirc

**Comment by CoryChaplin** [comment]
Hi Roberto,

You will need to develop a plugin that basically embeds the webcam system
you choose to use inside the client and manages the webcam sessions over
IRC.

-- 
Elephantman

De :  Ciro Roberto <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5b97cd9746326ff8d567d3fcc7ce630e03091133692cf00000001138453739
2a169ce09a8d676@reply.github.com>
Date :  vendredi 24 juin 2016 03:48
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Objet :  [prawnsalad/KiwiIRC] WebCam (#883)

**Comment by cirinho** [comment]
can be a direct point to point connection (not suggested)
or else a stream to relay (example: red5)

**Comment by CoryChaplin** [comment]
Sure, but you¹ll need to develop the plugin for yourself.

-- 
Elephantman

De :  Ciro Roberto <notifications@github.com>
Répondre à :  prawnsalad/KiwiIRC
<reply+004e6cd5572fd0abe9fb8ec1d9f2a802dabbf167947f610d92cf00000001138581259
2a169ce09a8d676@reply.github.com>
Date :  samedi 25 juin 2016 01:15
À :  prawnsalad/KiwiIRC <KiwiIRC@noreply.github.com>
Cc :  CORY CHAPLIN <elephantman@europnet.org>, Comment
<comment@noreply.github.com>
Objet :  Re: [prawnsalad/KiwiIRC] WebCam (#883)

**Comment by finalhit** [comment]
Anybody knows to implement this? Willing to fund it.

**Comment by cirinho** [comment]
It's what's missing.

with red5 looks great ... same as the late lightirc

**Comment by cirinho** [comment]
did anyone make it work?
https://github.com/kiwiirc/plugin-conference 
I think it's better to close

**Comment by jryberg** [comment]
I think this project is dead

Den sön 25 dec. 2022 14:24Ciro Moniz ***@***.***> skrev:
