### ISSUE TITLE
Make a user's original hostname available to the server.

### ISSUE THREAD

**Issue by AGausmann** [prawnsalad/KiwiIRC#900]
As a server operator as well as chanop in multiple miscellaneous channels, I became involved in an annoying situation where someone using a Kiwi IRC client is spamming and changing his nickname every time he connects. Since Kiwi is a proxy server and it generates usernames based on the nickname of the user, it is very hard to ban that person specifically (usually done by hostname) without banning everyone else using that client.

My suggestion is that Kiwi use the _hostname_ to generate a the user's username. If providing the hostname in plaintext is against the ideals of the client, then maybe use some kind of reversible hash. But please do something to allow operators to identify a Kiwi user by its originating host.

**Comment by prawnsalad** [comment]
Hi,

This is possible if you configure WEBIRC on your IRCd. It needs the extra configuration in your IRCd to whitelist the kiwi server for setting the users hostnames.

Using kiwiirc.com/client?
Register your network here: https://kiwiirc.com/enablekiwi

Using your own kiwi server?
https://kiwiirc.com/docs/installing/webirc
