### ISSUE TITLE
Safari fails to load assets when using SSL Kiwi Server

### ISSUE THREAD

**Issue by utoxin** [prawnsalad/KiwiIRC#903]
First, I am running the latest dev version now, but initially I was running a version a year or so old. The bug didn't change in behavior at all when I updated.

I recently got a cert for my site, so I configured Kiwi to use it. It works great in every browser except Safari. In Safari, it just sites on a white screen, and if I look at the error console and the network requests, what appears to be happening is that every request to Kiwi is returning the index.html file, regardless of what is actually being requested.

I've used the dev tools to 'Copy as curl', and when I run the curl commands they claim are equivalent, everything works just fine.

I've set up a non-SSL server on the same daemon, and it works fine in Safari.

The SSL server works fine in every browser except Safari.

I'm stumped. Any suggestions for solutions, or requests for additional information are welcome.

**Comment by prawnsalad** [comment]
If it's loading the index.html for the assets then that suggests the URLs are not being sent to the kiwi server correctly. But only on Safari? That doens't make much sense.

Is your kiwi server public somewhere so we can take a look?

**Comment by utoxin** [comment]
https://chatnano.net:7778/

**Comment by utoxin** [comment]
Out of curiosity, I just tried the example client on the Kiwi site, which is SSL, and it works. But it's also on the standard SSL port, so I'm wondering if that's part of it. Somehow.

**Comment by utoxin** [comment]
This has now expanded to Firefox. Which at least has better dev tools, not that they're helping. The request appears to be almost identical between Firefox (which fails) and Chrome (which works).

This seems like it has to be related to my setup somehow.... but I'm stumped about it. Do you want my config file?

**Comment by utoxin** [comment]
AHHA! I think I solved it. It may have been something out of date in NPM. I re-ran NPM install, and it seems to have started working for both Firefox and Safari.

**Comment by utoxin** [comment]
So. False alarm. With the weirdest manifestation ever. Thanks for trying to look at it so fast, and sorry for not thinking about running npm install again after I updated my checkout. It's on my checklist now.
