### ISSUE TITLE
Missing settings.json

### ISSUE THREAD

**Issue by Thetechie15** [prawnsalad/KiwiIRC#908]
I'm not sure what when wrong, I'm not that good with Node.js or anything. I compiled Kiwi from the git repo and followed the build instructions. I put the client folder on my site and it didn't load. Looking at the console "assets/settings.json" is missing. I don't know what I need to do to make that work or what. If someone could help, that'd be awesome. Thanks.
&emsp;&emsp;~Thethechie

**Comment by prawnsalad** [comment]
You don't upload the client files into your existing webserver. Kiwi IRC has its own web server built in as it handles IRC connections that traditional web servers can't do.

In the documentation, the `./kiwi start` command is what starts the webserver and dynamically generates the settings.json file.

If you must use Apache/Nginx or other webserver, you can run both together and proxy the kiwi server. Take a look here for info on that: https://kiwiirc.com/docs/installing/proxies
