### ISSUE TITLE
request textstyle update

### ISSUE THREAD

**Issue by Egypt-jumpper** [prawnsalad/KiwiIRC#931]
Hello there:
We need some update for plugin textstyle.html , we need loadSettings and saveSettings to localstorage in browser to save in browser window.localStorage.getItem , so when user reload pages the kiwi calls settings  from loacalStorage,
thnx,

**Comment by jnthnchagas** [comment]
Oh! I would be grateful

**Comment by driftypuddle** [comment]
would love to have this

**Comment by prawnsalad** [comment]
Tis version of Kiwi isn't getting any new features added, only bug fixes. The new version of kiwi that's under development can be found at https://github.com/kiwiirc/kiwiirc
