### ISSUE TITLE
How to set password on auto_connect?

### ISSUE THREAD

**Issue by anhofmann** [prawnsalad/KiwiIRC#947]
I want to pass the nick and the password to kiwiirc on startup. It works like this: https://my.server/kiwi/?nick=something but I can't add "&password=foobar". Is there a way to achieve this? I maintain a browser based mmorpg and use a flash based IRC client where every user has their own IRC server password which they don't need to type in (and mostly don't know). The chat loads in a iframe and connects automatically. Is it possible to do this with kiwiirc?

**Comment by prawnsalad** [comment]
I see that you created this issue on both this old version of the new version of kiwiirc. I've replied to your issue on the new version as this one is no longer worked on.

**Comment by anhofmann** [comment]
Yes i posted this on both projects because I'm not sure which one is the right one for me right now. The newer version seems to have some problems that might be a show stopper for my use case.
