### ISSUE TITLE
Return password handling to nextclient

### ISSUE THREAD

**Issue by dvorapa** [prawnsalad/KiwiIRC#948]
In old client there was a dialog next to the username for password. I can not see this in nextclient enywhere. There is some "password" input field, but it is not working for username passwords. Therefore the only possible way to identify is to write a command `/msg NickServ identify *password*`

**Comment by prawnsalad** [comment]
This is the old issue tracker, you will need to post new items on the new one here: https://github.com/kiwiirc/kiwiirc/issues

But for the password, it works in the exact same way as the old version. As long as the network supports SASL then it will log you into services.

**Comment by dvorapa** [comment]
I see, moved there
