### ISSUE TITLE
Has KiwiIRC ever been patched to work with cloudflare?

### ISSUE THREAD

**Issue by christoofar** [prawnsalad/KiwiIRC#959]
I'm using unrealircd and kiwi, behind nginx and cloudflare.

It connects maybe out of 1/20 tries.

**Comment by prawnsalad** [comment]
This version of kiwiirc has not been receiving updates for some time now, take a look at https://github.com/kiwiirc/kiwiirc

That said, both versions have been working behind cloudflare without issue for many people including myself. Make sure you're not using multiple upstreams in cloudflare and check your web logs for any issues coming up there.
