### ISSUE TITLE
Embedded client fails when localStorage unavailable

### ISSUE THREAD

**Issue by half-duplex** [prawnsalad/KiwiIRC#961]
In Chrome, when the user has disabled third party cookies, localStorage is unavailable to cross-domain javascript in an iframe. KiwiIRC (at least this version) fails to load when localStorage accesses cause exceptions. Wrapping all the localStorage mentions in `client/src/models/datastore.js` (attached) works, but is ignorant of any context or consequences of failure.
[datastore.js.txt](https://github.com/prawnsalad/KiwiIRC/files/4808890/datastore.js.txt)

**Comment by prawnsalad** [comment]
This version of kiwi isn't supported anymore. All development goes towards https://github.com/kiwiirc/kiwiirc
